# Generated by Django 5.1.5 on 2025-01-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
